version: '3.8'

services:
  task-db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  task-cache:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  task-api:
    build: .
    environment:
      DB_HOST: task-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: task_db
      DB_SSL_MODE: disable
      PORT: 3000
      SECRET_KEY: secret
      REDIS_CONNECTION_STRING: task-cache:6379
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "host=task-db port=5432 user=postgres password=postgres dbname=task_db sslmode=disable"
    ports:
      - "3000:3000"
    depends_on:
      task-db:
        condition: service_healthy
      task-cache:
        condition: service_started

volumes:
  pgdata: {}
  cache:
    driver: local
