version: '3.8'

services:
  task-db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: robinhood
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  task-api:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: robinhood
      PORT: 3000
      SECRET_KEY: secret
    ports:
      - "3000:3000"
    depends_on:
      - task-db

volumes:
  pgdata: {}
